development:
  directory: shopify-theme
  password: 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
  theme_id: "118864183458"
  store: drinkjade.myshopify.com

production:
  directory: shopify-theme
  password: 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
  theme_id: "108609798306"
  store: drinkjade.myshopify.com